const styles = {
  '.rbc-btn': { color: 'inherit', font: 'inherit', margin: '0' },
  'button.rbc-btn': {
    overflow: 'visible',
    textTransform: 'none',
    cursor: 'pointer',
  },
  'button[disabled].rbc-btn': { cursor: 'not-allowed' },
  'button.rbc-input::-moz-focus-inner': { border: '0', padding: '0' },
  '.rbc-calendar': {
    WebkitBoxSizing: 'border-box',
    boxSizing: 'border-box',
    height: '100%',
    display: 'flex',
    WebkitBoxOrient: 'vertical',
    WebkitBoxDirection: 'normal',
    msFlexDirection: 'column',
    flexDirection: 'column',
    WebkitBoxAlign: 'stretch',
    msFlexAlign: 'stretch',
    alignItems: 'stretch',
  },
  '.rbc-calendar *, .rbc-calendar *:before, .rbc-calendar *:after': {
    WebkitBoxSizing: 'inherit',
    boxSizing: 'inherit',
  },
  '.rbc-abs-full, .rbc-row-bg': {
    overflow: 'hidden',
    position: 'absolute',
    top: '0',
    left: '0',
    right: '0',
    bottom: '0',
  },
  '.rbc-ellipsis, .rbc-show-more, .rbc-row-segment .rbc-event-content, .rbc-event-label': {
    display: 'block',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  '.rbc-rtl': { direction: 'rtl' },
  '.rbc-off-range': { color: '#999999' },
  '.rbc-off-range-bg': { background: '#e6e6e6' },
  '.rbc-header': {
    overflow: 'hidden',
    WebkitBoxFlex: '1',
    msFlex: '1 0 0%',
    flex: '1 0 0%',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    padding: '0 3px',
    textAlign: 'center',
    verticalAlign: 'middle',
    fontWeight: 'bold',
    fontSize: '90%',
    minHeight: '0',
    borderBottom: '1px solid #ddd',
  },
  '.rbc-header + .rbc-header': { borderLeft: '1px solid #ddd' },
  '.rbc-rtl .rbc-header + .rbc-header': {
    borderLeftWidth: '0',
    borderRight: '1px solid #ddd',
  },
  '.rbc-header > a, .rbc-header > a:active, .rbc-header > a:visited': {
    color: 'inherit',
    textDecoration: 'none',
  },
  '.rbc-button-link': {
    color: 'inherit',
    background: 'none',
    margin: '0',
    padding: '0',
    border: 'none',
    cursor: 'pointer',
    WebkitUserSelect: 'text',
    MozUserSelect: 'text',
    msUserSelect: 'text',
    userSelect: 'text',
  },
  '.rbc-row-content': {
    position: 'relative',
    MozUserSelect: 'none',
    msUserSelect: 'none',
    userSelect: 'none',
    WebkitUserSelect: 'none',
    zIndex: 4,
  },
  '.rbc-row-content-scrollable': {
    display: 'flex',
    WebkitBoxOrient: 'vertical',
    WebkitBoxDirection: 'normal',
    msFlexDirection: 'column',
    flexDirection: 'column',
    height: '100%',
  },
  '.rbc-row-content-scrollable .rbc-row-content-scroll-container': {
    height: '100%',
    overflowY: 'scroll',
    msOverflowStyle: 'none',
    scrollbarWidth: 'none',
  },
  '.rbc-row-content-scrollable .rbc-row-content-scroll-container::-webkit-scrollbar': {
    display: 'none',
  },
  '.rbc-today': { backgroundColor: '#eaf6ff' },
  '.rbc-toolbar': {
    display: 'flex',
    msFlexWrap: 'wrap',
    flexWrap: 'wrap',
    WebkitBoxPack: 'center',
    msFlexPack: 'center',
    justifyContent: 'center',
    WebkitBoxAlign: 'center',
    msFlexAlign: 'center',
    alignItems: 'center',
    marginBottom: '10px',
    fontSize: '16px',
  },
  '.rbc-toolbar .rbc-toolbar-label': {
    WebkitBoxFlex: '1',
    msFlexPositive: '1',
    flexGrow: 1,
    padding: '0 10px',
    textAlign: 'center',
  },
  '.rbc-toolbar button': {
    color: '#373a3c',
    display: 'inline-block',
    margin: '0',
    textAlign: 'center',
    verticalAlign: 'middle',
    background: 'none',
    backgroundImage: 'none',
    border: '1px solid #ccc',
    padding: '0.375rem 1rem',
    borderRadius: '4px',
    lineHeight: 'normal',
    whiteSpace: 'nowrap',
  },
  '.rbc-toolbar button:active, .rbc-toolbar button.rbc-active': {
    backgroundImage: 'none',
    WebkitBoxShadow: 'inset 0 3px 5px rgba(0, 0, 0, 0.125)',
    boxShadow: 'inset 0 3px 5px rgba(0, 0, 0, 0.125)',
    borderColor: '#adadad',
  },
  '.rbc-toolbar button:active:hover, .rbc-toolbar button:active:focus, .rbc-toolbar button.rbc-active:hover, .rbc-toolbar button.rbc-active:focus': {
    color: '#373a3c',
    backgroundColor: '#d4d4d4',
    borderColor: '#8c8c8c',
  },
  '.rbc-toolbar button:focus': {
    color: '#373a3c',
    backgroundColor: '#e6e6e6',
    borderColor: '#adadad',
  },
  '.rbc-toolbar button:hover': {
    color: '#373a3c',
    backgroundColor: '#e6e6e6',
    borderColor: '#adadad',
  },
  '.rbc-btn-group': { display: 'inline-block', whiteSpace: 'nowrap' },
  '.rbc-btn-group > button:first-of-type:not(:last-child)': {
    borderTopRightRadius: '0',
    borderBottomRightRadius: '0',
  },
  '.rbc-btn-group > button:last-child:not(:first-of-type)': {
    borderTopLeftRadius: '0',
    borderBottomLeftRadius: '0',
  },
  '.rbc-rtl .rbc-btn-group > button:first-of-type:not(:last-child)': {
    borderRadius: '4px',
    borderTopLeftRadius: '0',
    borderBottomLeftRadius: '0',
  },
  '.rbc-rtl .rbc-btn-group > button:last-child:not(:first-of-type)': {
    borderRadius: '4px',
    borderTopRightRadius: '0',
    borderBottomRightRadius: '0',
  },
  '.rbc-btn-group > button:not(:first-of-type):not(:last-child)': {
    borderRadius: '0',
  },
  '.rbc-btn-group button + button': { marginLeft: '-1px' },
  '.rbc-rtl .rbc-btn-group button + button': {
    marginLeft: '0',
    marginRight: '-1px',
  },
  '.rbc-btn-group + .rbc-btn-group, .rbc-btn-group + button': {
    marginLeft: '10px',
  },
  '.rbc-event, .rbc-day-slot .rbc-background-event': {
    border: 'none',
    WebkitBoxSizing: 'border-box',
    boxSizing: 'border-box',
    WebkitBoxShadow: 'none',
    boxShadow: 'none',
    margin: '0',
    padding: '2px 5px',
    backgroundColor: '#3174ad',
    borderRadius: '5px',
    color: '#fff',
    cursor: 'pointer',
    width: '100%',
    textAlign: 'left',
  },
  '.rbc-slot-selecting .rbc-event, .rbc-slot-selecting .rbc-day-slot .rbc-background-event, .rbc-day-slot .rbc-slot-selecting .rbc-background-event':
    {
      cursor: 'inherit',
      pointerEvents: 'none',
    },
  '.rbc-event.rbc-selected, .rbc-day-slot .rbc-selected.rbc-background-event': {
    backgroundColor: '#265985',
  },
  '.rbc-event:focus, .rbc-day-slot .rbc-background-event:focus': {
    outline: '5px auto #3b99fc',
  },
  '.rbc-event-label': { fontSize: '80%' },
  '.rbc-event-overlaps': {
    WebkitBoxShadow: '-1px 1px 5px 0px rgba(51, 51, 51, 0.5)',
    boxShadow: '-1px 1px 5px 0px rgba(51, 51, 51, 0.5)',
  },
  '.rbc-event-continues-prior': {
    borderTopLeftRadius: '0',
    borderBottomLeftRadius: '0',
  },
  '.rbc-event-continues-after': {
    borderTopRightRadius: '0',
    borderBottomRightRadius: '0',
  },
  '.rbc-event-continues-earlier': {
    borderTopLeftRadius: '0',
    borderTopRightRadius: '0',
  },
  '.rbc-event-continues-later': {
    borderBottomLeftRadius: '0',
    borderBottomRightRadius: '0',
  },
  '.rbc-row': {
    display: 'flex',
    WebkitBoxOrient: 'horizontal',
    WebkitBoxDirection: 'normal',
    msFlexDirection: 'row',
    flexDirection: 'row',
  },
  '.rbc-row-segment': { padding: '0 1px 1px 1px' },
  '.rbc-selected-cell': { backgroundColor: 'rgba(0, 0, 0, 0.1)' },
  '.rbc-show-more': {
    backgroundColor: 'rgba(255, 255, 255, 0.3)',
    zIndex: 4,
    fontWeight: 'bold',
    fontSize: '85%',
    height: 'auto',
    lineHeight: 'normal',
    color: '#3174ad',
  },
  '.rbc-show-more:hover, .rbc-show-more:focus': { color: '#265985' },
  '.rbc-month-view': {
    position: 'relative',
    border: '1px solid #ddd',
    display: 'flex',
    WebkitBoxOrient: 'vertical',
    WebkitBoxDirection: 'normal',
    msFlexDirection: 'column',
    flexDirection: 'column',
    WebkitBoxFlex: '1',
    msFlex: '1 0 0px',
    flex: '1 0 0',
    width: '100%',
    MozUserSelect: 'none',
    msUserSelect: 'none',
    userSelect: 'none',
    WebkitUserSelect: 'none',
    height: '100%',
  },
  '.rbc-month-header': {
    display: 'flex',
    WebkitBoxOrient: 'horizontal',
    WebkitBoxDirection: 'normal',
    msFlexDirection: 'row',
    flexDirection: 'row',
  },
  '.rbc-month-row': {
    display: 'flex',
    position: 'relative',
    WebkitBoxOrient: 'vertical',
    WebkitBoxDirection: 'normal',
    msFlexDirection: 'column',
    flexDirection: 'column',
    WebkitBoxFlex: '1',
    msFlex: '1 0 0px',
    flex: '1 0 0',
    msFlexPreferredSize: '0px',
    flexBasis: '0px',
    overflow: 'hidden',
    height: '100%',
  },
  '.rbc-month-row + .rbc-month-row': { borderTop: '1px solid #ddd' },
  '.rbc-date-cell': {
    WebkitBoxFlex: '1',
    msFlex: '1 1 0px',
    flex: '1 1 0',
    minWidth: '0',
    paddingRight: '5px',
    textAlign: 'right',
  },
  '.rbc-date-cell.rbc-now': { fontWeight: 'bold' },
  '.rbc-date-cell > a, .rbc-date-cell > a:active, .rbc-date-cell > a:visited': {
    color: 'inherit',
    textDecoration: 'none',
  },
  '.rbc-row-bg': {
    display: 'flex',
    WebkitBoxOrient: 'horizontal',
    WebkitBoxDirection: 'normal',
    msFlexDirection: 'row',
    flexDirection: 'row',
    WebkitBoxFlex: '1',
    msFlex: '1 0 0px',
    flex: '1 0 0',
    overflow: 'hidden',
  },
  '.rbc-day-bg': { WebkitBoxFlex: '1', msFlex: '1 0 0%', flex: '1 0 0%' },
  '.rbc-day-bg + .rbc-day-bg': { borderLeft: '1px solid #ddd' },
  '.rbc-rtl .rbc-day-bg + .rbc-day-bg': {
    borderLeftWidth: '0',
    borderRight: '1px solid #ddd',
  },
  '.rbc-overlay': {
    position: 'absolute',
    zIndex: 5,
    border: '1px solid #e5e5e5',
    backgroundColor: '#fff',
    WebkitBoxShadow: '0 5px 15px rgba(0, 0, 0, 0.25)',
    boxShadow: '0 5px 15px rgba(0, 0, 0, 0.25)',
    padding: '10px',
  },
  '.rbc-overlay > * + *': { marginTop: '1px' },
  '.rbc-overlay-header': {
    borderBottom: '1px solid #e5e5e5',
    margin: '-10px -10px 5px -10px',
    padding: '2px 10px',
  },
  '.rbc-agenda-view': {
    display: 'flex',
    WebkitBoxOrient: 'vertical',
    WebkitBoxDirection: 'normal',
    msFlexDirection: 'column',
    flexDirection: 'column',
    WebkitBoxFlex: '1',
    msFlex: '1 0 0px',
    flex: '1 0 0',
    overflow: 'auto',
  },
  '.rbc-agenda-view table.rbc-agenda-table': {
    width: '100%',
    border: '1px solid #ddd',
    borderSpacing: '0',
    borderCollapse: 'collapse',
  },
  '.rbc-agenda-view table.rbc-agenda-table tbody > tr > td': {
    padding: '5px 10px',
    verticalAlign: 'top',
  },
  '.rbc-agenda-view table.rbc-agenda-table .rbc-agenda-time-cell': {
    paddingLeft: '15px',
    paddingRight: '15px',
    textTransform: 'lowercase',
  },
  '.rbc-agenda-view table.rbc-agenda-table tbody > tr > td + td': {
    borderLeft: '1px solid #ddd',
  },
  '.rbc-rtl .rbc-agenda-view table.rbc-agenda-table tbody > tr > td + td': {
    borderLeftWidth: '0',
    borderRight: '1px solid #ddd',
  },
  '.rbc-agenda-view table.rbc-agenda-table tbody > tr + tr': {
    borderTop: '1px solid #ddd',
  },
  '.rbc-agenda-view table.rbc-agenda-table thead > tr > th': {
    padding: '3px 5px',
    textAlign: 'left',
    borderBottom: '1px solid #ddd',
  },
  '.rbc-rtl .rbc-agenda-view table.rbc-agenda-table thead > tr > th': {
    textAlign: 'right',
  },
  '.rbc-agenda-time-cell': { textTransform: 'lowercase' },
  '.rbc-agenda-time-cell .rbc-continues-after:after': { content: "' »'" },
  '.rbc-agenda-time-cell .rbc-continues-prior:before': { content: "'« '" },
  '.rbc-agenda-date-cell, .rbc-agenda-time-cell': { whiteSpace: 'nowrap' },
  '.rbc-agenda-event-cell': { width: '100%' },
  '.rbc-time-column': {
    display: 'flex',
    WebkitBoxOrient: 'vertical',
    WebkitBoxDirection: 'normal',
    msFlexDirection: 'column',
    flexDirection: 'column',
    minHeight: '100%',
  },
  '.rbc-time-column .rbc-timeslot-group': {
    WebkitBoxFlex: '1',
    msFlex: '1',
    flex: 1,
  },
  '.rbc-timeslot-group': {
    borderBottom: '1px solid #ddd',
    minHeight: '40px',
    display: 'flex',
    WebkitBoxOrient: 'vertical',
    WebkitBoxDirection: 'normal',
    msFlexFlow: 'column nowrap',
    flexFlow: 'column nowrap',
  },
  '.rbc-time-gutter, .rbc-header-gutter': {
    WebkitBoxFlex: '0',
    msFlex: 'none',
    flex: 'none',
  },
  '.rbc-label': { padding: '0 5px' },
  '.rbc-day-slot': { position: 'relative' },
  '.rbc-day-slot .rbc-events-container': {
    bottom: '0',
    left: '0',
    position: 'absolute',
    right: '0',
    marginRight: '10px',
    top: '0',
  },
  '.rbc-day-slot .rbc-events-container.rbc-rtl': { left: '10px', right: '0' },
  '.rbc-day-slot .rbc-event, .rbc-day-slot .rbc-background-event': {
    border: '1px solid #265985',
    display: 'flex',
    maxHeight: '100%',
    minHeight: '20px',
    WebkitBoxOrient: 'vertical',
    WebkitBoxDirection: 'normal',
    msFlexFlow: 'column wrap',
    flexFlow: 'column wrap',
    WebkitBoxAlign: 'start',
    msFlexAlign: 'start',
    alignItems: 'flex-start',
    overflow: 'hidden',
    position: 'absolute',
  },
  '.rbc-day-slot .rbc-background-event': { opacity: 0.75 },
  '.rbc-day-slot .rbc-event-label': {
    WebkitBoxFlex: '0',
    msFlex: 'none',
    flex: 'none',
    paddingRight: '5px',
    width: 'auto',
  },
  '.rbc-day-slot .rbc-event-content': {
    width: '100%',
    WebkitBoxFlex: '1',
    msFlex: '1 1 0px',
    flex: '1 1 0',
    wordWrap: 'break-word',
    lineHeight: 1,
    height: '100%',
    minHeight: '1em',
  },
  '.rbc-day-slot .rbc-time-slot': { borderTop: '1px solid #f7f7f7' },
  '.rbc-time-view-resources .rbc-time-gutter, .rbc-time-view-resources .rbc-time-header-gutter': {
    position: 'sticky',
    left: '0',
    backgroundColor: 'white',
    borderRight: '1px solid #ddd',
    zIndex: 10,
    marginRight: '-1px',
  },
  '.rbc-time-view-resources .rbc-time-header': { overflow: 'hidden' },
  '.rbc-time-view-resources .rbc-time-header-content': {
    minWidth: 'auto',
    WebkitBoxFlex: '1',
    msFlex: '1 0 0px',
    flex: '1 0 0',
    msFlexPreferredSize: '0px',
    flexBasis: '0px',
  },
  '.rbc-time-view-resources .rbc-time-header-cell-single-day': {
    display: 'none',
  },
  '.rbc-time-view-resources .rbc-day-slot': { minWidth: '140px' },
  '.rbc-time-view-resources .rbc-header, .rbc-time-view-resources .rbc-day-bg': {
    width: '140px',
    WebkitBoxFlex: '1',
    msFlex: '1 1 0px',
    flex: '1 1 0',
    msFlexPreferredSize: '0 px',
    flexBasis: '0 px',
  },
  '.rbc-time-header-content + .rbc-time-header-content': { marginLeft: '-1px' },
  '.rbc-time-slot': { WebkitBoxFlex: '1', msFlex: '1 0 0px', flex: '1 0 0' },
  '.rbc-time-slot.rbc-now': { fontWeight: 'bold' },
  '.rbc-day-header': { textAlign: 'center' },
  '.rbc-slot-selection': {
    zIndex: 10,
    position: 'absolute',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    color: 'white',
    fontSize: '75%',
    width: '100%',
    padding: '3px',
  },
  '.rbc-slot-selecting': { cursor: 'move' },
  '.rbc-time-view': {
    display: 'flex',
    WebkitBoxOrient: 'vertical',
    WebkitBoxDirection: 'normal',
    msFlexDirection: 'column',
    flexDirection: 'column',
    WebkitBoxFlex: '1',
    msFlex: '1',
    flex: 1,
    width: '100%',
    border: '1px solid #ddd',
    minHeight: '0',
  },
  '.rbc-time-view .rbc-time-gutter': {
    whiteSpace: 'nowrap',
    textAlign: 'right',
  },
  '.rbc-time-view .rbc-allday-cell': {
    WebkitBoxSizing: 'content-box',
    boxSizing: 'content-box',
    width: '100%',
    height: '100%',
    position: 'relative',
  },
  '.rbc-time-view .rbc-allday-cell + .rbc-allday-cell': {
    borderLeft: '1px solid #ddd',
  },
  '.rbc-time-view .rbc-allday-events': { position: 'relative', zIndex: 4 },
  '.rbc-time-view .rbc-row': {
    WebkitBoxSizing: 'border-box',
    boxSizing: 'border-box',
    minHeight: '20px',
  },
  '.rbc-time-header': {
    display: 'flex',
    WebkitBoxFlex: '0',
    msFlex: '0 0 auto',
    flex: '0 0 auto',
    WebkitBoxOrient: 'horizontal',
    WebkitBoxDirection: 'normal',
    msFlexDirection: 'row',
    flexDirection: 'row',
  },
  '.rbc-time-header.rbc-overflowing': { borderRight: '1px solid #ddd' },
  '.rbc-rtl .rbc-time-header.rbc-overflowing': {
    borderRightWidth: '0',
    borderLeft: '1px solid #ddd',
  },
  '.rbc-time-header > .rbc-row:first-of-type': { borderBottom: '1px solid #ddd' },
  '.rbc-time-header > .rbc-row.rbc-row-resource': {
    borderBottom: '1px solid #ddd',
  },
  '.rbc-time-header-cell-single-day': { display: 'none' },
  '.rbc-time-header-content': {
    WebkitBoxFlex: '1',
    msFlex: '1',
    flex: 1,
    display: 'flex',
    minWidth: '0',
    WebkitBoxOrient: 'vertical',
    WebkitBoxDirection: 'normal',
    msFlexDirection: 'column',
    flexDirection: 'column',
    borderLeft: '1px solid #ddd',
  },
  '.rbc-rtl .rbc-time-header-content': {
    borderLeftWidth: '0',
    borderRight: '1px solid #ddd',
  },
  '.rbc-time-header-content > .rbc-row.rbc-row-resource': {
    borderBottom: '1px solid #ddd',
    msFlexNegative: '0',
    flexShrink: 0,
  },
  '.rbc-time-content': {
    display: 'flex',
    WebkitBoxFlex: '1',
    msFlex: '1 0 0%',
    flex: '1 0 0%',
    WebkitBoxAlign: 'start',
    msFlexAlign: 'start',
    alignItems: 'flex-start',
    width: '100%',
    borderTop: '2px solid #ddd',
    overflowY: 'auto',
    position: 'relative',
  },
  '.rbc-time-content > .rbc-time-gutter': {
    WebkitBoxFlex: '0',
    msFlex: 'none',
    flex: 'none',
  },
  '.rbc-time-content > * + * > *': { borderLeft: '1px solid #ddd' },
  '.rbc-rtl .rbc-time-content > * + * > *': {
    borderLeftWidth: '0',
    borderRight: '1px solid #ddd',
  },
  '.rbc-time-content > .rbc-day-slot': {
    width: '100%',
    MozUserSelect: 'none',
    msUserSelect: 'none',
    userSelect: 'none',
    WebkitUserSelect: 'none',
  },
  '.rbc-current-time-indicator': {
    position: 'absolute',
    zIndex: 3,
    left: '0',
    right: '0',
    height: '1px',
    backgroundColor: '#74ad31',
    pointerEvents: 'none',
  },
  '.react-calendar': {
    width: '350px',
    maxWidth: '100%',
    background: 'white',
    border: '1px solid #a0a096',
    fontFamily: "'Montserrat', sans-serif",
    lineHeight: '1.125em',
  },
  '.react-calendar--doubleView': { width: '700px' },
  '.react-calendar--doubleView .react-calendar__viewContainer': {
    display: 'flex',
    margin: '-0.5em',
  },
  '.react-calendar--doubleView .react-calendar__viewContainer > *': {
    width: '50%',
    margin: '0.5em',
  },
  '.react-calendar, .react-calendar *, .react-calendar *:before, .react-calendar *:after': {
    fontFamily: "'Montserrat', sans-serif",
    MozBoxSizing: 'border-box',
    WebkitBoxSizing: 'border-box',
    boxSizing: 'border-box',
  },
  '.react-calendar button': { margin: '0', border: '0', outline: 'none' },
  '.react-calendar button:enabled:hover': { cursor: 'pointer' },
  '.react-calendar__navigation': {
    display: 'flex',
    height: '60px !important',
    marginBottom: '1em',
  },
  '.react-calendar__navigation button': {
    minWidth: '44px',
    background: 'none',
  },
  '.react-calendar__navigation button:disabled': { backgroundColor: '#f0f0f0' },
  '.react-calendar__navigation button:enabled:hover, .react-calendar__navigation button:enabled:focus': {
    backgroundColor: '#e6e6e6',
  },
  '.react-calendar__month-view__weekdays': {
    textAlign: 'center',
    textTransform: 'uppercase',
    fontWeight: 'bold',
    fontSize: '0.75em',
  },
  '.react-calendar__month-view__weekdays__weekday': { padding: '0.5em' },
  '.react-calendar__month-view__weekNumbers .react-calendar__tile': {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '0.75em',
    fontWeight: 'bold',
  },
  '.react-calendar__month-view__days__day--weekend': { color: '#d10000' },
  '.react-calendar__month-view__days__day--neighboringMonth': {
    color: '#757575',
  },
  '.react-calendar__year-view .react-calendar__tile, .react-calendar__decade-view .react-calendar__tile, .react-calendar__century-view .react-calendar__tile':
    {
      padding: '2em 0.5em',
    },
  '.react-calendar__tile': {
    maxWidth: '100%',
    padding: '10px 6.6667px',
    background: 'none',
    textAlign: 'center',
    lineHeight: '16px',
    fontFamily: "'Montserrat', sans-serif",
    fontSize: '15px',
  },
  '.react-calendar__tile:disabled': { backgroundColor: '#f0f0f0' },
  '.react-calendar__tile:enabled:hover, .react-calendar__tile:enabled:focus': {
    backgroundColor: '#e6e6e6',
  },
  '.react-calendar__tile--now': { background: '#ffff76' },
  '.react-calendar__tile--now:enabled:hover, .react-calendar__tile--now:enabled:focus': {
    background: '#ffffa9',
  },
  '.react-calendar__tile--hasActive': { background: '#76baff' },
  '.react-calendar__tile--hasActive:enabled:hover, .react-calendar__tile--hasActive:enabled:focus': {
    background: '#a9d4ff',
  },
  '.react-calendar__tile--active': { background: '#006edc', color: 'white' },
  '.react-calendar__tile--active:enabled:hover, .react-calendar__tile--active:enabled:focus': {
    background: '#1087ff',
  },
  '.react-calendar--selectRange .react-calendar__tile--hover': {
    backgroundColor: '#e6e6e6',
  },
  '.react-calendar__tile--active, .react-calendar__tile--active:enabled:hover, .react-calendar__tile--active:enabled:focus': {
    border: '2px solid grey !important',
    background: 'inherit !important',
  },
  '.react-calendar__tile--active abbr': { color: 'black' },
  '.react-calendar__navigation__label span': {
    fontSize: '16px',
    height: '30px',
  },
  '.react-calendar__navigation__next-button, .react-calendar__navigation__prev-button': {
    fontSize: '30px',
    fontWeight: 'bold',
    padding: '0',
    color: 'black',
  },
};

export default styles;
